DROP TABLE IF EXISTS `acme`;
CREATE TABLE `acme` (
`certificate` VARCHAR(8192) NOT NULL,
`private_key` VARCHAR(4096) NOT NULL,
`created_at` DATETIME(3) NOT NULL DEFAULT 0,
`expire_at` DATETIME(3) NOT NULL DEFAULT 0
) ENGINE = INNODB CHARSET = utf8mb4;