// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/storage/create_asset": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传文件",
                "tags": [
                    "storage"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点区域",
                        "name": "area_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件名",
                        "name": "asset_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件cid",
                        "name": "asset_cid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "节点id",
                        "name": "node_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件类型",
                        "name": "asset_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "文件大小",
                        "name": "asset_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "group id",
                        "name": "group_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{[]{CandidateAddr:\"\",Token:\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传文件",
                "tags": [
                    "storage"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "description": "请求参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.createAssetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{[]{CandidateAddr:\"\",Token:\"\"}}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/create_group": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建文件夹",
                "tags": [
                    "storage"
                ],
                "summary": "创建文件夹",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "父级id",
                        "name": "parent",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{group:{}}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/create_key": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建key",
                "tags": [
                    "storage"
                ],
                "summary": "创建key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key name",
                        "name": "key_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{key:\"\",secret:\"\"}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/create_link": {
            "get": {
                "description": "获取分享链接",
                "tags": [
                    "storage"
                ],
                "summary": "获取分享链接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件cid",
                        "name": "cid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{url: \"\"}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/delete_asset": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除文件",
                "tags": [
                    "storage"
                ],
                "summary": "删除文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点区域",
                        "name": "area_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件cid",
                        "name": "asset_cid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{msg:\"\"}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/delete_key": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除key",
                "tags": [
                    "storage"
                ],
                "summary": "删除key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "key name",
                        "name": "key_name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{msg:\"\"}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_area_id": {
            "get": {
                "description": "获取调度器的 area id 列表",
                "tags": [
                    "storage"
                ],
                "summary": "获取调度器的 area id 列表",
                "responses": {
                    "200": {
                        "description": "{list:[]}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_asset_group_list": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取文件夹列表信息，包含其中的文件信息",
                "tags": [
                    "storage"
                ],
                "summary": "获取文件夹列表信息，包含其中的文件信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "父级id",
                        "name": "parent",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{list:{},total:0}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_asset_info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传文件",
                "tags": [
                    "storage"
                ],
                "summary": "上传文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点区域",
                        "name": "area_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件cid",
                        "name": "cid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{{list:[],total:0}}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_groups": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取文件夹列表",
                "tags": [
                    "storage"
                ],
                "summary": "获取文件夹列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "父级id",
                        "name": "parent",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page_size",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page",
                        "name": "page",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{list:{},total:0}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_keys": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取key列表",
                "tags": [
                    "storage"
                ],
                "summary": "获取key列表",
                "responses": {
                    "200": {
                        "description": "{list:[{name:\"\",key:\"\",secret:\"\",time:\"\"}]}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_link": {
            "get": {
                "description": "获取分享链接",
                "tags": [
                    "storage"
                ],
                "summary": "获取分享链接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "username",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "url",
                        "name": "url",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件cid",
                        "name": "cid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{url: \"\"}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_map_cid": {
            "get": {
                "description": "获取cid map",
                "tags": [
                    "storage"
                ],
                "summary": "获取cid map",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件cid",
                        "name": "cid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{url: \"\"}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_storage_size": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取用户存储空间信息",
                "tags": [
                    "storage"
                ],
                "summary": "获取用户存储空间信息",
                "responses": {
                    "200": {
                        "description": "{PeakBandwidth:0,TotalTraffic:0,TotalSize:0,UsedSize:0}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/get_vip_info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "判断用户是否是vip",
                "tags": [
                    "storage"
                ],
                "summary": "判断用户是否是vip",
                "responses": {
                    "200": {
                        "description": "{vip:false}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/rename_asset": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "文件重命名",
                "tags": [
                    "storage"
                ],
                "summary": "文件重命名",
                "responses": {
                    "200": {
                        "description": "{\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/rename_group": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "文件重命名",
                "tags": [
                    "storage"
                ],
                "summary": "文件重命名",
                "responses": {
                    "200": {
                        "description": "{\"msg\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/share_asset": {
            "get": {
                "description": "分享文件",
                "tags": [
                    "storage"
                ],
                "summary": "分享文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "节点区域",
                        "name": "area_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "文件cid",
                        "name": "asset_cid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{asset_cid: \"\",redirect:\"\",url:{}}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/temp_file/download/{cid}": {
            "get": {
                "description": "下载首页上传文件",
                "tags": [
                    "temp_file"
                ],
                "summary": "下载首页上传文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件的cid",
                        "name": "cid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/temp_file/info/{cid}": {
            "get": {
                "description": "获取上传详情",
                "tags": [
                    "temp_file"
                ],
                "summary": "获取上传详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件的cid",
                        "name": "cid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{total:0,cid:\"\",share_url:[]{}}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        },
        "/api/v1/storage/temp_file/upload": {
            "post": {
                "description": "首页上传文件，如果返回的为空数组，则不调用上传接口",
                "tags": [
                    "temp_file"
                ],
                "summary": "首页上传文件",
                "parameters": [
                    {
                        "description": "文件上传参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UploadTempFileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{[]{CandidateAddr: “”, Token: “”}}",
                        "schema": {
                            "$ref": "#/definitions/api.JsonObject"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.JsonObject": {
            "type": "object",
            "additionalProperties": true
        },
        "api.UploadTempFileReq": {
            "type": "object",
            "required": [
                "asset_cid",
                "asset_name",
                "asset_size"
            ],
            "properties": {
                "area_ids": {
                    "description": "最多3个",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "asset_cid": {
                    "type": "string"
                },
                "asset_name": {
                    "type": "string"
                },
                "asset_size": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "string"
                }
            }
        },
        "api.createAssetRequest": {
            "type": "object",
            "required": [
                "asset_name",
                "asset_size",
                "asset_type"
            ],
            "properties": {
                "area_id": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "asset_cid": {
                    "type": "string"
                },
                "asset_name": {
                    "type": "string"
                },
                "asset_size": {
                    "type": "integer"
                },
                "asset_type": {
                    "type": "string"
                },
                "encrypted": {
                    "type": "boolean"
                },
                "group_id": {
                    "type": "integer"
                },
                "node_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Titan Explorer API",
	Description:      "This is titan explorer backend server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
